### ISSUE TITLE
Nominating David Harding and Fiacc O'Brien Moran as contributors

### ISSUE THREAD

**Issue by jasnell** [covidgreen/covid-green-app#19]
@covidgreen/members ... David Harding (@dharding) and Fiacc (@fiacc) are both involved in the New York State tracker adaptation and will be contributing here (Fiacc actually has been contributing for a while as part of the NearForm team). Nominating them both as @covidgreen/members for commit access. 

Please 👍🏻 or 👎🏻 on the nomination.

**Comment by aspiringarc** [comment]
👍

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ShaunBaker** [comment]
👍

**Comment by jasnell** [comment]
Ok @dharding and @fiacc ... I've added you both to the @covidgreen/members team which gives you write access to the repository. Please be sure to review the CONTRIBUTING.md guide (which, right now is a rough starter that likely will evolve once we continue to get bootstrapped) and the Code of Conduct.

When you get a moment, please open PRs to add yourselves to the contributors list in each of the project repos.
