### ISSUE TITLE
Contact Tracing Status Icon in Tab Bar

### ISSUE THREAD

**Issue by jasnell** [covidgreen/covid-green-app#3]
For a second or two when the app launches, while the app is determining the enabled/disabled state of the "Contact Tracing" mechanism, the icon on the tab bar displays the "ct-off-unselected" ![ct-off-unselected](https://github.com/covidgreen/covid-green-app/blob/current/assets/images/contact-tracing/ct-off-unselected.png?raw=true) icon, giving the momentary appearance that the service is not enabled or not functioning. Users have reported that this is confusing.

It would be ideal for the app to launch with an initial "ct-unknown-unselected" icon that is visually differentiated from the disabled state.

Relevant code location: https://github.com/covidgreen/covid-green-app/blob/current/components/organisms/tab-bar-bottom.tsx

User tweet:

![image](https://user-images.githubusercontent.com/439929/87991721-a1b5a880-ca9b-11ea-86a6-3224e8fe7639.png)

**Comment by SeanTheShaman** [comment]
I would like to work on this feature.

**Comment by jh3y** [comment]
Are you working on this feature @SeanTheShaman?
